name: Main

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: plugin-release
          path: build/distributions/nginx-intellij-plugin-*.zip
          retention-days: 3
